# These are supported funding model platforms

github: silpol 
# patreon: name
open_collective: silpol
ko_fi: silpol
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # silpol
liberapay: silpol
issuehunt: silpol
custom: ['https://paypal.me/silpol4paypal ','https://www.buymeacoffee.com/silpol']
 # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
